<template>
  <div>
    <div class="navbar text-focus-in">
      <ul class="ul-flex">
        <a :href="links[0].href">
          <img :src="links[0].image" alt height="46px;" />
        </a>
        <li
          v-for="(link, index) in links.slice(1)"
          :key="index"
          class="li-flex"
        >
          <a :href="link.href" class="a-flex">{{ link.name }}</a>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      links: [
        {
          name: "",
          href: "#",
          image:
            "https://firebasestorage.googleapis.com/v0/b/adp-cv.appspot.com/o/base%2Fadam-logo.jpg?alt=media&token=2aa71b01-e382-4c1e-b29f-184a44b73e3a"
        },
        { name: "MyStory", href: "#Story" },
        { name: "MySkills", href: "#Skills" },
        { name: "MyWorks", href: "#Works" }
      ]
    };
  }
};
</script>

<style lang="scss" scoped>
img {
  padding-left: 10px;
}
.ul-flex {
  display: flex;
  flex-direction: row;
  justify-content: space-evenly;
  align-items: center;
  flex-wrap: wrap;
  list-style-type: none;
  padding: 0;
  margin: 0;
}
.li-flex {
  flex: 1 1 90px;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  height: 50px;
}
.a-flex {
  padding: 5px;
  color: black;
  display: inline-block;
  position: relative;
  overflow: hidden;
  text-decoration: none;
  color: black;
  border-radius: 10px;
  box-sizing: border-box;
  border: 2px solid transparent;
}
.a-flex::before {
  content: "";
  position: absolute;
  z-index: -1;
  left: 51%;
  right: 51%;
  bottom: 0;
  background: #2098d1;
  height: 4px;
  transition-property: left, right;
  transition-duration: 0.5s;
  transition-timing-function: ease-out;
}
.a-flex:hover::before,
.a-flex:focus::before,
.a-flex:active::before {
  left: 0;
  right: 0;
}
.a-flex:hover {
  border: 1px solid #2098d1;
}

.navbar {
  background: white;
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  z-index: 200;
  height: auto;
}
.text-focus-in {
  -webkit-animation: text-focus-in 2s cubic-bezier(0.55, 0.085, 0.68, 0.53) 0.5s
    both;
  animation: text-focus-in 2s cubic-bezier(0.55, 0.085, 0.68, 0.53) 0.5s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2019-4-4 13:31:10
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
</style>
